algo = input('Digite algo: ')
print('O tipo primitivo desse valor é de:', type(algo))
print('Só tem espaços?', algo.isspace())
print('É um número?', algo.isnumeric())
print('é um alfabético?', algo.isalpha())
print('É um alfanumérico?', algo.isalnum())
print('Está em maipusculas?', algo.isupper())
print('Está em minúsculas?', algo.islower())
print('Ela está capitalizada?', algo.istitle())